# Use Python 3.10 slim image
FROM python:3.10-slim

# Copy the requirements file and install dependencies
COPY ./celeryApp/requirements.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
# Install the custom kafka client
COPY ./kafkaClient ./kafkaClient
RUN pip install -e ./kafkaClient
# Copy the rest of the application code
COPY ./celeryApp ./

CMD ["celery", "-A", "celery_app", "worker", "--loglevel=debug"]
 