apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\matte\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: decision-app-service
  name: decision-app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: decision-app-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\matte\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: decision-app-service
    spec:
      containers:
        - image: mchianale/decision-app-service
          name: decision-app-service
          ports:
            - containerPort: 8003
              protocol: TCP
          stdin: true
          tty: true
      restartPolicy: Always
