apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: kafka-2-data
  name: kafka-2-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
