apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: krabbitmq-data
  name: krabbitmq-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
