apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\matte\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: kredis
  name: kredis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kredis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\matte\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: kredis
    spec:
      containers:
        - args:
            - redis-server
            - --requirepass
            - b2ecc628566048608451c61b6b210ee6467edc7aefa911efafe4e4c7673f17a8
          env:
            - name: REDIS_PASSWORD
              value: b2ecc628566048608451c61b6b210ee6467edc7aefa911efafe4e4c7673f17a8
          image: redis:latest
          name: kredis
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: kredis-data
      restartPolicy: Always
      volumes:
        - name: kredis-data
          persistentVolumeClaim:
            claimName: kredis-data
